### ISSUE TITLE
SyncDnsResolver用正则过滤纯IP会不会多此一举 (

### ISSUE THREAD

**Issue by Kr328** [rtdarwin/ProxyBench#1]
gataddrinfo 会更好的处理 IP 
用正则反而拉低性能 
虽然并不重要 (

**Comment by rtdarwin** [comment]
我写混了。。。

本来我用的 socks5 而不是 socks5h 代理，当本地解析 google.com 为 IPv6 地址时，远程服务器就访问不了。所以我一股脑的把项目里面所有 DNS 解析相关的东西都改成 IPv4 only 了，想避免 IPv6 的问题。

SyncDnsResolver 也被我改成 IPv4 only 了。但调用 getaddrinfo 的时候如果传一个 addrinfo.ai_family = AF_INET 的 hints，getaddinfo 就无法处理纯数字 IP 地址，所以。。。我就用了一个正则匹配了一下。。。

现在看来，这样做对 IPv6 更不友好了。。。
